### ISSUE TITLE
Practica4_calculadora en consola

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-topicosavanzados-ide#1]

**Comment by EdwinOrtiz1412** [comment]
[Practica 4_4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-topicosavanzados-ide/files/8281781/Practica.4_4US.pdf)

**Comment by IrvingFernand0** [comment]
[Uploading Practica 4_4US.pdf…]()

**Comment by IrvingFernand0** [comment]
[Practica 4_4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-topicosavanzados-ide/files/8281801/Practica.4_4US.pdf)

**Comment by Gregorio012** [comment]
Calificación 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
