### ISSUE TITLE
Practica 4_Irving Fernando Reyes pacheco

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-topicosavanzados-ide#5]
[Practica 4.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-topicosavanzados-ide/files/8832077/Practica.4.pdf)

**Comment by EvelynLopezz** [comment]
Calificación 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
